name: Run PowerShell script check
on: [push, pull_request]

jobs:
  pwsh-lint:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: PSScriptAnalyzer
        shell: pwsh
        run: |
          Install-Module PSScriptAnalyzer -Force
          Invoke-ScriptAnalyzer -Path . -Recurse -Severity Information
